project_id = "udnaflcohfyljrsgqggy"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://udnaflcohfyljrsgqggy.supabase.co"]

[auth.email]
enable_signup = true

[functions.ai-deck-builder]
verify_jwt = false

[functions.ai-deck-builder-v2]
verify_jwt = false

[functions.gemini-deck-coach]
verify_jwt = false

[functions.mtg-brain]
verify_jwt = false

[functions.edh-power-check]
verify_jwt = false
