import puppeteer from 'puppeteer';
const b=await puppeteer.launch({headless:'new',args:['--no-sandbox']});
const p=await b.newPage(); await p.setViewport({width:1440,height:900});
p.on('response',async r=>{ if(r.url().includes('api.scryfall.com')) console.log(r.status(), decodeURIComponent(r.url()).slice(0,140)); });
await p.goto('http://127.0.0.1:8080/',{waitUntil:'networkidle2',timeout:90000});
await new Promise(r=>setTimeout(r,1500));
const box=await p.$('#home-search'); await box.scrollIntoView(); await new Promise(r=>setTimeout(r,1000));
await box.click({clickCount:3}); await p.keyboard.press('Backspace');
await p.type('#home-search','Atraxa, Praetors Voice',{delay:30});
await new Promise(r=>setTimeout(r,4000));
console.log('value=',await p.$eval('#home-search',e=>e.value));
console.log(await p.evaluate(()=>document.getElementById('home-search').closest('section').innerText.slice(0,300)));
await b.close();
