/**
 * Every keyword a player can ask the meaning of, because a card in our
 * catalogue prints Wizards' own definition of it.
 *
 * GENERATED. Do not edit by hand.
 *   deno run --allow-net --allow-write --allow-env scripts/tutor-keyword-vocabulary.ts
 *
 * NAMES ONLY, AND THAT IS THE POINT. A definition is read off a card every time
 * somebody asks, by `answer/glossary.ts`. Writing the definitions down here
 * would be a copy that can drift from the card, and the card is the authority.
 *
 * A name is here only when at least one card OPENS a line of its rules text
 * with that keyword and a bracket, which is what a reminder text looks like.
 * Measured 2026-08-29 over 5,734 cards carrying such a line, from
 * 8,339 rows of `cards_unique` that carry a keyword and a bracket.
 *
 * Sorted by how many cards back each one, most first.
 */

export const KEYWORD_NAMES: string[] = [
  "Cycling",
  "Equip",
  "Kicker",
  "Flashback",
  "Morph",
  "Menace",
  "Devoid",
  "Defender",
  "Convoke",
  "Flash",
  "Reach",
  "Crew",
  "Flying",
  "Partner",
  "Trample",
  "Prowess",
  "Changeling",
  "Lifelink",
  "Cumulative upkeep",
  "Suspend",
  "Vigilance",
  "Shadow",
  "Madness",
  "Unearth",
  "Haste",
  "Deathtouch",
  "Ninjutsu",
  "Ward",
  "Infect",
  "Foretell",
  "Hexproof",
  "Toxic",
  "Bestow",
  "Cascade",
  "Echo",
  "Fear",
  "Rebound",
  "Swampwalk",
  "Islandwalk",
  "Choose a background",
  "Station",
  "Basic landcycling",
  "Bushido",
  "Soulshift",
  "First strike",
  "Megamorph",
  "Warp",
  "Overload",
  "Plot",
  "Backup",
  "Exalted",
  "Forestwalk",
  "Doctor's companion",
  "Evoke",
  "Flanking",
  "Shroud",
  "Delve",
  "Mutate",
  "Storm",
  "Buyback",
  "Split second",
  "Blitz",
  "Bloodthirst",
  "Entwine",
  "Horsemanship",
  "Intimidate",
  "Sneak",
  "Soulbond",
  "Teamwork",
  "Disguise",
  "Wither",
  "Dash",
  "Living weapon",
  "Spree",
  "Undying",
  "Offspring",
  "Persist",
  "Modular",
  "Ascend",
  "Cipher",
  "Retrace",
  "Saddle",
  "Affinity",
  "Level Up",
  "Myriad",
  "Cleave",
  "Gift",
  "Improvise",
  "Job select",
  "Tribute",
  "Awaken",
  "Encore",
  "Exploit",
  "Learn",
  "Mayhem",
  "Mentor",
  "Battle Cry",
  "Devour",
  "Double strike",
  "Emerge",
  "Evolve",
  "Fading",
  "Miracle",
  "Multikicker",
  "Assist",
  "Enchant",
  "Jump",
  "Jump-start",
  "Sunburst",
  "Vanishing",
  "Bargain",
  "Mountainwalk",
  "Reconfigure",
  "Skulk",
  "Surge",
  "Transmute",
  "Amass",
  "Graft",
  "Outlast",
  "Renown",
  "Replicate",
  "Scavenge",
  "Unleash",
  "Harmonize",
  "Increment",
  "Melee",
  "Mobilize",
  "Casualty",
  "Dredge",
  "Enlist",
  "Fabricate",
  "Freerunning",
  "Phasing",
  "Plainscycling",
  "Riot",
  "Conspire",
  "Protection",
  "Ravenous",
  "Read Ahead",
  "Squad",
  "Training",
  "Champion",
  "Dethrone",
  "Embalm",
  "Escalate",
  "Firebending",
  "Hidden agenda",
  "Indestructible",
  "Reinforce",
  "Spectacle",
  "Storied",
  "Surveil",
  "Umbra armor",
  "Web-slinging",
  "Annihilator",
  "Banding",
  "Forestcycling",
  "Islandcycling",
  "Mountaincycling",
  "Paradigm",
  "Swampcycling",
  "Augment",
  "Demonstrate",
  "Extort",
  "Investigate",
  "Prototype",
  "Prowl",
  "Haunt",
  "Hideaway",
  "Ripple",
  "Afflict",
  "Amplify",
  "Compleated",
  "Eternalize",
  "Provoke",
  "Rampage",
  "Support",
  "Afterlife",
  "Ingest",
  "Plainswalk",
  "Recover",
  "Tiered",
  "Decayed",
  "Epic",
  "Time Travel",
  "Wizardcycling",
  "Commander ninjutsu",
  "Fortify",
  "Hexproof from",
  "Proliferate",
  "Undaunted",
  "Gravestorm",
  "Partner with",
  "Populate",
  "Slivercycling",
  "Bolster",
  "Desertwalk",
  "Double",
  "Double agenda",
  "Earthbend",
  "Frenzy",
  "Impending",
  "Incubate",
  "Legendary landwalk",
  "Manifest",
  "Manifest dread",
  "Scry",
  "Transfigure",
];
