/**
 * DeckMatrix — the XMage runtime API: the SHARED effect classes a card body
 * constructs and then runs.
 *
 * ## Licence and attribution
 *
 * Behaviour here is derived from **XMage**, which is MIT licensed,
 * `Copyright (c) 2010 betasteward@gmail.com`, https://github.com/magefree/mage.
 * The clone is read in place, outside this repository; nothing from it is
 * vendored. XMage's display strings are never copied: those carry Wizards of
 * the Coast rules text, which is not XMage's to license, so every log line
 * below is ours. Forge is GPL-3.0 and was not fetched, read or referenced.
 *
 * ## Why this file exists, and it is the caveat in RUNTIME-API.md section 3
 *
 * `Game#addEffect` has counted as implemented since the first tranche, and the
 * CALL is: it appends an `ADD_CONTINUOUS` action. Its ARGUMENT is a shared
 * effect class — `new BoostTargetEffect(2, 2)`, `new CreateTokenEffect(new
 * SoldierToken())` — and each of those is its own porting job. This file is
 * where those jobs land.
 *
 * The distinction that keeps the numbers honest: a card-local body lives in
 * `bodies.generated.ts` and is MACHINE TRANSLATED. These are HAND written,
 * because a shared class is called by hundreds of cards and a machine
 * translation of one would be wrong in hundreds of places at once.
 *
 * ## Two kinds of effect, and they are not interchangeable
 *
 * XMage spells both as `Effect`, so a body reads the same either way, and the
 * difference decides what comes out:
 *
 * - A **one-shot** does something now. `.apply(game, source)` emits actions.
 * - A **continuous** effect is handed to `game.addEffect(effect, source)`, which
 *   stores it. Nothing happens at the moment it is built, and its target
 *   pointer may be set after construction, so it cannot resolve its own targets
 *   until `addEffect` asks it to.
 *
 * That is why a continuous builder here carries `build(game, source)` rather
 * than resolving eagerly: `new BoostTargetEffect(2, 2).setTargetPointer(...)`
 * is two statements in XMage and the pointer arrives on the second one.
 */

import type { InstanceId, PlayerId } from '../types.ts';
import type { ContinuousEffect, EffectExpiry, LayerSelector } from '../layers.ts';
import type { XmageScope } from './runtime.ts';
import { deferHere, derivedId } from './runtime.ts';
import type { XGame, XToken, XTokenSpec } from './objects.ts';
import { makeToken } from './objects.ts';
import type { XAbility, XEffect, XTargetPointer } from './targets.ts';
/*
 * The token table, generated by `scripts/xmage/extract-tokens.mjs` from XMage's
 * own 793 token classes. A value import across into `cards/`, which is the same
 * direction `objects.ts` already takes for `TokenSpec`; `tokens.generated.ts`
 * imports one type and nothing else, so there is no cycle.
 */
import { XMAGE_TOKENS } from '../../cards/xmage/tokens.generated.ts';

/* -------------------------------------------------------------------------- */
/* Continuous effects                                                         */
/* -------------------------------------------------------------------------- */

/**
 * An effect that is STORED rather than run. `game.addEffect` recognises one by
 * `buildContinuous` and asks it for the record to store.
 *
 * The brand is a method rather than a boolean flag so that a plain
 * `ContinuousEffect` — which is pure data and has no methods at all — can never
 * be mistaken for one, and vice versa.
 */
export interface XContinuousBuilder extends XEffect {
  buildContinuous(game: XGame, source: XAbility): ContinuousEffect | null;
}

/**
 * XMage's `Duration`, as this engine's `EffectExpiry`.
 *
 * `WhileOnBattlefield` and `Custom` are deliberately absent. The first is
 * `while-source`, which needs a source id the duration alone does not carry, so
 * the caller supplies it; the second is XMage saying "the effect decides", and
 * guessing which end it meant is exactly the confident wrong answer this port
 * refuses.
 */
export type XDuration = 'EndOfTurn' | 'EndOfGame' | 'UntilYourNextTurn' | 'WhileOnBattlefield';

export function expiryFor(
  duration: XDuration | undefined,
  scope: XmageScope,
  controllerId: PlayerId
): EffectExpiry {
  switch (duration) {
    case 'EndOfGame':
      return { kind: 'never' };
    case 'UntilYourNextTurn':
      return { kind: 'your-next-turn', controllerId, afterTurn: scope.working.turn };
    case 'WhileOnBattlefield':
      return { kind: 'while-source' };
    case 'EndOfTurn':
    default:
      /*
       * `EndOfTurn` is XMage's own default on every boost constructor that does
       * not name one, so defaulting here is not a guess about the card: it is
       * the same default, in the same place.
       */
      return { kind: 'end-of-turn', turn: scope.working.turn };
  }
}

/**
 * The permanents an effect is about, as a layer selector.
 *
 * `null` when the pointer bound nothing. That is not the same as "affects
 * nothing": the pointer itself already said out loud that nothing was bound
 * (see `pointerOverTargets` in `targets.ts`), and storing an effect with an
 * empty id list would be a continuous effect that silently modifies no object
 * for the rest of the turn.
 */
function selectorFor(ids: readonly InstanceId[]): LayerSelector | null {
  if (ids.length === 0) return null;
  return { kind: 'match', ids: [...ids] };
}

const sign = (n: number): string => (n >= 0 ? `+${n}` : `${n}`);

/** Where a boost gets the permanents it boosts. The one thing that varies. */
type Recipients = (source: XAbility, pointer: XTargetPointer | undefined) => InstanceId[];

const POINTED: Recipients = (source, pointer) =>
  (pointer ?? source.getTargetPointer()).getTargets();

const THE_SOURCE: Recipients = source => [source.getSourceId()];

/**
 * XMage's `BoostTargetEffect` — "target creature gets +2/+2 until end of turn",
 * and 54 card-local bodies build one directly.
 *
 * The boost is LOCKED IN at the moment it is stored, which is XMage's own
 * behaviour: `init` replaces a dynamic value with the number it calculated once
 * the effect is not tracking a changing set. Epic Fight doubles the creature's
 * power as it was when the spell resolved, not as it is later.
 */
export function boostTargetEffect(
  scope: XmageScope,
  power: number,
  toughness: number,
  duration?: XDuration,
  recipients: Recipients = POINTED
): XContinuousBuilder {
  let pointer: XTargetPointer | undefined;
  const effect: XContinuousBuilder = {
    setTargetPointer(next) {
      pointer = next;
      return effect;
    },
    getTargetPointer: () => pointer,
    buildContinuous(_game, source) {
      const affects = selectorFor(recipients(source, pointer));
      if (!affects) return null;
      const names = (affects.kind === 'match' ? (affects.ids ?? []) : [])
        .map(id => scope.working.cards[id]?.name ?? id);
      const subject = names.length === 0 ? 'It' : names.join(', ');
      const verb = names.length === 1 ? 'gets' : 'get';
      return {
        id: derivedId(scope, 'boost'),
        timestamp: scope.options.timestamp ?? scope.working.version ?? 0,
        sourceId: source.getSourceId(),
        controllerId: source.getControllerId(),
        affects,
        parts: [
          {
            sublayer: '7c',
            modification: { kind: 'modify-pt', power, toughness },
          },
        ],
        provides: ['modify-pt'],
        // Ours, not XMage's. Its own `getText` is Wizards wording.
        note: `${subject} ${verb} ${sign(power)}/${sign(toughness)}`,
        expiry: expiryFor(duration, scope, source.getControllerId()),
      };
    },
    /*
     * XMage's `ContinuousEffectImpl.apply` is called by the effect ENGINE on
     * every layer pass, never by a card body — a body hands the effect to
     * `game.addEffect` instead. A body that calls it directly has done
     * something this port does not model, so it says so rather than quietly
     * boosting nothing.
     */
    apply() {
      deferHere(
        scope,
        'a continuous effect was run directly instead of being added to the game, which this engine does not model'
      );
      return false;
    },
  };
  return effect;
}

/**
 * `BoostSourceEffect` — the same thing pointed at the ability's own source.
 * 24 bodies. It takes no target pointer, so one is fixed here.
 */
export function boostSourceEffect(
  scope: XmageScope,
  power: number,
  toughness: number,
  duration?: XDuration
): XContinuousBuilder {
  return boostTargetEffect(scope, power, toughness, duration, THE_SOURCE);
}

/* -------------------------------------------------------------------------- */
/* Tokens                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * One of XMage's token classes, by class name, as an `XToken`.
 *
 * ## Why the class name and not a spec
 *
 * `new SoldierToken()` is 127 bodies' first blocker across 101 distinct
 * classes, so on the work order it is a hundred tiny rows and never appears as
 * one line. It is one mapping: `extract-tokens.mjs` already parsed 741 of
 * XMage's 793 token classes into `tokens.generated.ts`, and this reads that
 * table. Nothing about a token is transcribed here.
 *
 * ## The two things it refuses
 *
 * **A class the table does not hold.** The generated table is the only source,
 * and a missing entry raises rather than falling back on a 1/1 — a wrong token
 * on the board looks exactly like a right one, and there is no later moment
 * where anybody could notice. The translator checks the table at generate time
 * as well, so a body naming a missing class never reaches this file; this guard
 * is the second lock on the same door.
 *
 * **A constructor with arguments.** The table holds the NO-ARGUMENT
 * constructor. `new PhyrexianRebirthHorrorToken(count, count)` sizes the token
 * from the board, and handing it the no-argument spec would create a token of
 * the wrong size in silence. Nine of the 127 are written that way and the
 * translator blocks every one of them by name.
 *
 * ## What it says out loud
 *
 * 191 of the 741 classes add an ability a `TokenSpec` cannot carry, which is
 * why `extract-tokens.mjs` records `otherAbilities` rather than dropping them: a
 * Treasure token with no sacrifice ability looks exactly like one that works.
 * The token is still created, because a 2/2 Zombie on the board is most of what
 * the card said and creating nothing would be less of it. The missing half is
 * declared, so the behaviour probe downgrades the card instead of counting it.
 */
export function xmageToken(scope: XmageScope, className: string): XToken {
  const entry = XMAGE_TOKENS[className];
  if (!entry) {
    throw new Error(
      `xmageToken: no token class "${className}" in the generated table. The translator is meant to block this body.`
    );
  }
  if (entry.otherAbilities.length > 0) {
    const n = entry.otherAbilities.length;
    deferHere(
      scope,
      `the ${entry.spec.name} token was created without ${n} ${n === 1 ? 'ability' : 'abilities'} this engine cannot give a token yet`
    );
  }
  return makeToken(scope, entry.spec);
}

/**
 * XMage's `CreateTokenEffect`. 54 card-local bodies build one, and a further
 * 127 stop one step earlier on the token class it takes.
 *
 * `apply` returns true unconditionally, which is XMage's own answer: creating a
 * token always happens. `getLastAddedTokenIds` reads the ids back off the board,
 * because 17 of those bodies do something to the tokens afterwards.
 */
export interface XCreateTokenEffect extends XEffect {
  getLastAddedTokenIds(): InstanceId[];
  exileTokensCreatedAtNextEndStep(game: XGame, source: XAbility): void;
  removeTokensCreatedAt(game: XGame, source: XAbility): void;
  withAdditionalTokens(...tokens: XToken[]): XCreateTokenEffect;
  entersWithCounters(counterType: string, count: number): XCreateTokenEffect;
}

export function createTokenEffect(
  scope: XmageScope,
  token: XToken,
  amount: number = 1,
  tapped: boolean = false,
  attacking: boolean = false
): XCreateTokenEffect {
  const tokens: XToken[] = [token];
  let lastAdded: InstanceId[] = [];
  let counter: { type: string; count: number } | null = null;
  let pointer: XTargetPointer | undefined;

  const effect: XCreateTokenEffect = {
    apply(game, source) {
      lastAdded = [];
      if (amount <= 0) {
        /*
         * XMage's own `apply` returns true whatever the count, and a count of
         * zero is a real answer — "create a token for each creature that died"
         * on a turn nothing died. Nothing is created and nothing is claimed.
         */
        return true;
      }
      if (attacking) {
        /*
         * "Create a token tapped and attacking" chooses a defender and puts the
         * token into an existing combat. This engine has no action that adds an
         * attacker after attackers are declared, so the token arrives tapped and
         * NOT attacking, and the difference — a creature that was going to deal
         * damage this turn and now is not — is said rather than swallowed.
         */
        deferHere(
          scope,
          'the token was created tapped but not attacking, which this engine cannot do mid-combat'
        );
      }
      const controllerId = source.getControllerId();
      for (const each of tokens) {
        each.putOntoBattlefield(amount, controllerId, tapped || attacking);
        lastAdded = [...lastAdded, ...each.getLastAddedTokenIds()];
      }
      if (counter) {
        for (const id of lastAdded) {
          game.getPermanent(id)?.addCounters(counter.type, counter.count);
        }
      }
      return true;
    },
    getLastAddedTokenIds: () => [...lastAdded],
    /*
     * CR 603.7. Both of these set up a delayed triggered ability, and this
     * engine has no store for one, so they defer for exactly the reason
     * `Game#addDelayedTriggeredAbility` does: a silent success would be a card
     * that appeared to set something up and never fired it. The tokens are on
     * the board and they will not leave.
     */
    exileTokensCreatedAtNextEndStep() {
      deferHere(
        scope,
        'the tokens were created but the delayed trigger that removes them cannot be stored yet, so they will not leave'
      );
    },
    removeTokensCreatedAt() {
      deferHere(
        scope,
        'the tokens were created but the delayed trigger that removes them cannot be stored yet, so they will not leave'
      );
    },
    withAdditionalTokens(...more) {
      tokens.push(...more);
      return effect;
    },
    entersWithCounters(counterType, count) {
      counter = { type: counterType, count };
      return effect;
    },
    setTargetPointer(next) {
      pointer = next;
      return effect;
    },
    getTargetPointer: () => pointer,
  };
  return effect;
}
