-- APPLIED 4 Sep 2026. DO NOT RUN THIS FILE. It is a record of what was done.
--
-- Running it would DROP a `cards_pool` that already carries the change, and it
-- would do it the slow way. The version of this file that existed before was
-- `begin; drop; create; index; commit;`, and the CREATE populates while holding
-- ACCESS EXCLUSIVE on the name every deck-generator request reads. That is an
-- outage, not a migration.
--
-- ===========================================================================
-- WHAT THE CHANGE IS
-- ===========================================================================
--
-- 1. THE TAG MERGE MAY NOT OVERWRITE THE COMPILER'S PRECISION.
--
--    `cards_pool.facets` is `compiler_facets || tag_facets` and neither source
--    knows what the other said. Where the compiler emitted the PRECISE `-self`
--    variant, a gated tag adding the GENERIC verb put back the very
--    distinction the compiler had been taught to draw.
--
--    The rule: drop a TAG facet X when the compiler emitted X-self and did NOT
--    emit X. It never removes anything the compiler said, never touches a card
--    the compiler was silent about, and fires only where a tag flattens a
--    distinction the compiler drew.
--
--    Measured before applying: 429 cards of the 25,790 carrying tags, dropping
--    ctr:+1/+1, eff:add-counters, eff:damage, eff:discard and eff:exile -
--    exactly the five pairs this codebase built `-self` variants for. Animar
--    and Korvold both stop reading as Hardened Scales decks.
--
-- 2. `grants:` COUNTS AS KNOWING WHAT A CARD DOES.
--
--    156 cards whose entire job is giving an ability were filed under "knows
--    nothing": Leyline of Anticipation, Shimmer Myr, Vedalken Orrery. ONLY the
--    label changed. The identical regex in the `merged` CTE decides which tag
--    words a card ACCEPTS, and changing that would be a behaviour change
--    wearing a reporting fix's clothes.
--
-- The view also moved from facet compiler_version 16 to 17.
--
-- ===========================================================================
-- HOW IT WAS APPLIED
-- ===========================================================================
--
-- Alongside and swap, so nothing the product reads was locked for more than
-- milliseconds:
--
--   1. create materialized view cards_pool_next as (...) WITH NO DATA;
--      Instant, no lock on the live view, reversible by dropping it.
--   2. the five indexes, plus grant select to anon, authenticated, service_role
--   3. refresh materialized view cards_pool_next;      -- 33,035 rows
--   4. verify (below)
--   5. begin; drop cards_pool; rename next -> cards_pool; rename 5 indexes; commit;
--   6. analyze public.cards_pool;
--
-- THE EIGHT MINUTE FIGURE WAS WRONG. 501,867 ms is `cards_unique` AND
-- `cards_pool` refreshed CONCURRENTLY, which builds a temp table and diffs a
-- live view. A PLAIN refresh of one matview finished inside the 120 s session,
-- so the pg_cron route planned for it was never needed.
--
-- THE GRANTS WERE A BLOCKER THIS FILE DID NOT HANDLE. `cards_pool` carries
-- explicit grants to anon, authenticated and service_role, and a DROP destroys
-- them: the recreated view would have been owner-only and PostgREST would have
-- returned permission denied for every generator request, silently. Measured,
-- the ACL matches the default privilege for `postgres` creating a table in
-- `public` EXACTLY and the applying session IS postgres, so the new matview
-- inherited them. The explicit GRANT went in anyway and both ACLs were
-- compared and found identical BEFORE the swap.
--
-- ===========================================================================
-- VERIFIED BEFORE THE SWAP RATHER THAN AFTER
-- ===========================================================================
--
--   rows          33,035 both sides
--   columns       15, identical in name, ORDER and type
--   indexes       5, copied from pg_indexes rather than remembered
--   grants        identical ACL on both objects
--   null facets   0
--
--   still both add-counters and -self   1,161 -> 748
--                 (the 748 are cards whose COMPILER said both, which the rule
--                  correctly preserves; 413 were fixed)
--   eff:create-token                    2,863 -> 3,138
--   knows nothing about what it does      401 -> 324
--   the app knows what it does          97.3% -> 97.9%
--
-- After: 14 of 14 deployed decks build, 82/94 staples, 3,357 tests passing.
--
-- ===========================================================================
-- IF IT EVER NEEDS DOING AGAIN
-- ===========================================================================
--
-- Regenerate the definition from `pg_get_viewdef('public.cards_pool')` rather
-- than from this file. Copy the index definitions from `pg_indexes` rather
-- than remembering them: the first draft of this file guessed FOUR and got
-- three wrong, inventing one on `name` and missing the GIN index on
-- `color_identity` and the rank index entirely. Check the pinned
-- `compiler_version` still matches the constant in `facet-memo-fill`.
--
-- The old compiler version can go once the generator has been exercised
-- against the new one:
--   delete from public.card_facet_memo where compiler_version = 16;

select 'applied 4 Sep 2026 by an alongside-and-swap; see the header' as note;
